name: Publish PR Preview Package

on:
    pull_request:
        branches: [main]

jobs:
    publish-preview:
        runs-on: ubuntu-latest
        environment:
            name: npm
            
        steps:
            - uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 10
                  run_install: false

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Generate preview version
              run: |
                  pr_number=${{ github.event.pull_request.number }}
                  npm version prerelease --preid=pr-${pr_number} --no-git-tag-version

            - name: Publish to npm
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH }}
              run: npm publish --tag pr-${{ github.event.pull_request.number }} --access public

            - name: Comment on PR
              uses: marocchino/sticky-pull-request-comment@v2
              with:
                  message: |
                      📦 Preview package for this PR is published!

                      Install it with:
                      ```bash
                      npm install svelteplot@pr-${{ github.event.pull_request.number }}
                      ```
