name: Publish PR Preview Package

on:
    pull_request:
        branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
    test:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 10
                  run_install: false

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Run Vitest tests
              run: pnpm test
              
    publish-preview:
        # Prevent this job from running on forks
        if: github.repository == 'svelteplot/svelteplot'
        needs: test
        runs-on: ubuntu-latest
        environment:
            name: npm
            
        steps:
            - uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 10
                  run_install: false

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'pnpm'
                  registry-url: "https://registry.npmjs.org"

            - name: Install dependencies
              run: pnpm install

            - name: Generate preview version
              run: |
                  pr_number=${{ github.event.pull_request.number }}
                  
                  # Check if a prerelease version for this PR already exists on npm
                  existing_versions=$(npm view svelteplot versions --json 2>/dev/null | grep -o "\".*pr-${pr_number}[.][0-9]*\"" || echo "")
                  
                  if [ -n "$existing_versions" ]; then
                    # Get the latest prerelease version for this PR
                    latest_version=$(echo $existing_versions | sed 's/,/\n/g' | sort -V | tail -n 1 | sed 's/"//g')
                    echo "Found existing prerelease version: $latest_version"
                    
                    # Set the package version to the existing version so npm version will properly increment
                    npm version $latest_version --no-git-tag-version
                  fi
                  
                  # Now increment the prerelease version (or create it if it doesn't exist)
                  npm version prerelease --preid=pr-${pr_number} --no-git-tag-version
                  
                  echo "Generated version: $(node -p "require('./package.json').version")"

            - name: Publish to npm
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH }}
              run: npm publish --tag pr-${{ github.event.pull_request.number }} --access public

            # Save version for use in PR comment
            - name: Save version
              run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
              
            - name: Comment on PR
              uses: peter-evans/create-or-update-comment@v3
              with:
                  issue-number: ${{ github.event.pull_request.number }}
                  body: |
                      📦 Preview package for this PR is published!
                      
                      Version: `${{ env.PACKAGE_VERSION }}`

                      Install it with:
                      ```bash
                      npm install svelteplot@pr-${{ github.event.pull_request.number }}
                      # or install the specific version
                      npm install svelteplot@${{ env.PACKAGE_VERSION }}
                      ```
                  reactions: '+1, rocket'
                  edit-mode: replace
